# SPDX-License-Identifier: MIT
# rules.py - curated, language-agnostic error knowledge base for `whyex`.
# Author: Sai Koushik Yaganti (https://github.com/SAI141003)
# Each rule: id, tags, match (regex string), title, why, fix (list of steps).
# Templates may use {name} placeholders filled from named regex groups.

RULES = [
    {
        "id": "git-not-a-repo",
        "tags": ["git"],
        "severity": "error",
        "match": r"fatal: not a git repository",
        "title": "Not inside a Git repository",
        "why": "The command needs a .git folder but the current directory isn't tracked by Git (or you're above the repo root).",
        "fix": [
            "Initialize a new repo here: `git init`.",
            "Or cd into the existing project: `cd /path/to/repo` (or `git clone <url>` to fetch it).",
        ],
        "remediation": "git init",
    },
    {
        "id": "git-push-rejected",
        "tags": ["git"],
        "severity": "error",
        "match": r"failed to push some refs|non-fast-forward|Updates were rejected",
        "title": "Push rejected: remote has work you don't have",
        "why": "Someone else pushed commits to the branch. Git refuses to overwrite their history.",
        "fix": [
            "Pull first: `git pull --rebase origin <branch>`",
            "Resolve any conflicts, then `git push origin <branch>`.",
        ],
    },
    {
        "id": "git-refspec",
        "tags": ["git"],
        "severity": "error",
        "match": r"src refspec .* does not match any|unknown revision or path not in the working tree",
        "title": "Git can't find the branch/ref you named",
        "why": "The branch you're trying to push/pull doesn't exist locally yet.",
        "fix": [
            "Check the branch name: `git branch`.",
            "To push a new local branch: `git push -u origin <branch>`.",
        ],
    },
    {
        "id": "git-remote-exists",
        "tags": ["git"],
        "severity": "error",
        "match": r"remote origin already exists",
        "title": "`origin` remote already exists",
        "why": "You tried to add a remote named `origin` but one is already configured.",
        "fix": [
            "See existing remotes: `git remote -v`.",
            "To change the URL: `git remote set-url origin <new-url>`.",
        ],
    },
    {
        "id": "git-ssh-permission",
        "tags": ["git", "ssh"],
        "severity": "error",
        "match": r"Permission denied \(publickey\)|Could not read from remote repository",
        "title": "SSH key not accepted by the remote",
        "why": "The Git host can't authenticate you - your SSH public key isn't added or the agent isn't running.",
        "fix": [
            "Start the agent: `eval $(ssh-agent)` then `ssh-add ~/.ssh/id_ed25519`.",
            "Add your public key (`cat ~/.ssh/id_ed25519.pub`) to your Git host's SSH keys.",
            "Or switch to HTTPS: `git remote set-url origin https://...`.",
        ],
    },
    {
        "id": "git-detached",
        "tags": ["git"],
        "severity": "error",
        "match": r"detached HEAD|you are in 'detached HEAD'",
        "title": "You're in a detached HEAD state",
        "why": "You checked out a commit (not a branch), so new commits won't belong to a branch.",
        "fix": [
            "Create/switch to a branch to keep your work: `git switch -c <new-branch>`.",
            "Or return to your branch: `git switch <branch>`.",
        ],
        "remediation": "git switch -c <new-branch>",
    },
    {
        "id": "git-divergent",
        "tags": ["git"],
        "severity": "error",
        "match": r"Pulling without specifying how to reconcile",
        "title": "Git wants to know how to merge after a pull",
        "why": "Your branch and its upstream have diverged; Git needs a merge/rebase strategy.",
        "fix": [
            "Configure once: `git config pull.rebase true` (or false for merge).",
            "Then `git pull`.",
        ],
        "remediation": "git config pull.rebase true",
    },
    {
        "id": "git-untracked-overwrite",
        "tags": ["git"],
        "severity": "error",
        "match": r"untracked working tree files would be overwritten|The following untracked working tree files",
        "title": "Checkout would overwrite untracked files",
        "why": "Files exist locally that Git would clobber with incoming versions.",
        "fix": [
            "Stash them: `git stash -u`, then retry, then `git stash pop`.",
            "Or move/delete the listed untracked files if they're not needed.",
        ],
    },
    {
        "id": "py-modulenotfound",
        "tags": ["python"],
        "severity": "error",
        "match": r"ModuleNotFoundError: No module named ['\"]?(?P<mod>[^'\"]+)",
        "title": "Missing Python package: {mod}",
        "why": "The import failed because Python can't find the module in the interpreter currently running - either your venv isn't activated or the package truly isn't installed.",
        "fix": [
            "Confirm the right interpreter is active: `which python` (macOS/Linux) / `where python` (Windows).",
            "If a venv isn't activated, `source venv/bin/activate` (or `venv\\Scripts\\activate` on Windows).",
            "Install with the same interpreter: `python -m pip install {mod}` (use `python -m` so it targets the active env, not a stray `pip`).",
            "Verify it's importable: `python -m pip show {mod}`; if found but still failing, you're running a different interpreter.",
        ],
    },
    {
        "id": "py-syntaxerror",
        "tags": ["python"],
        "severity": "error",
        "match": r"SyntaxError:",
        "title": "Python syntax error",
        "why": "The parser hit code it can't compile - usually a typo, missing colon, unbalanced brackets/quotes, or a stray character.",
        "fix": [
            "Read the line number the traceback points to; check for a missing `:`, unbalanced `()`, `[]`, `{}`, or unclosed string quotes.",
            "Compile to pinpoint it: `python -m py_compile yourfile.py` (reports file:line of the error).",
        ],
    },
    {
        "id": "py-indentation",
        "tags": ["python"],
        "severity": "error",
        "match": r"IndentationError:",
        "title": "Python indentation error",
        "why": "Python is whitespace-sensitive; mixing tabs and spaces, or inconsistent indent widths, makes a block ambiguous.",
        "fix": [
            "Use spaces only (PEP 8 recommends 4 spaces) - never mix tabs and spaces; configure your editor to insert spaces.",
            "Find the bad lines: `python -m tabnanny yourfile.py`.",
        ],
    },
    {
        "id": "py-filenotfound",
        "tags": ["python", "files"],
        "severity": "error",
        "match": r"FileNotFoundError: \[Errno 2\] No such file or directory",
        "title": "File or directory not found",
        "why": "Your code opened a path that doesn't exist (often a relative path issue).",
        "fix": [
            "Print the absolute path: `os.path.abspath('your/file')` to see what's being opened.",
            "Use paths relative to the script: `os.path.join(os.path.dirname(__file__), 'file')`.",
        ],
    },
    {
        "id": "py-unicode",
        "tags": ["python", "encoding"],
        "severity": "error",
        "match": r"UnicodeDecodeError:",
        "title": "Unicode decode error while reading text",
        "why": "The file isn't UTF-8 (often Latin-1/Windows-1252) but you read it as UTF-8.",
        "fix": [
            "Open with an explicit encoding: `open(path, encoding='latin-1')` (or `encoding='utf-8', errors='replace'`).",
            "Detect the real encoding with the `chardet` package if unsure.",
        ],
    },
    {
        "id": "py-pip-permission",
        "tags": ["python", "pip"],
        "severity": "error",
        "match": r"error: externally-managed-environment|Consider using the `--user` option|PermissionError: \[Errno 13\]",
        "title": "pip can't write to the system Python",
        "why": "Your OS protects the global Python via PEP 668 (externally-managed-environment), or you lack write permission to site-packages.",
        "fix": [
            "Best: isolate with a virtual env: `python -m venv venv && source venv/bin/activate` then `pip install <pkg>`.",
            "Alt: per-user install `pip install --user <pkg>`; for CLI tools prefer `pipx install <pkg>`.",
            "Never run `sudo pip install` - it corrupts the system Python. If truly global, use the distro package manager.",
        ],
        "remediation": "python -m venv venv && source venv/bin/activate && pip install <pkg>",
    },
    {
        "id": "py-python-not-found",
        "tags": ["python"],
        "severity": "error",
        "match": r"python: command not found|command not found: python\b|'python' is not recognized",
        "title": "`python` command not found",
        "why": "Many systems only ship `python3`; the bare `python` alias is missing.",
        "fix": [
            "Use `python3` instead of `python`.",
            "Or create an alias / symlink, or via pyenv: `pyenv global 3.x`.",
        ],
        "remediation": 'ln -s "$(command -v python3)" /usr/local/bin/python   # or use python3 directly',
    },
    {
        "id": "node-not-found",
        "tags": ["node"],
        "severity": "error",
        "match": r"node: command not found|command not found: node|'node' is not recognized",
        "title": "Node.js is not installed",
        "why": "The `node` binary isn't on your PATH.",
        "fix": [
            "Install Node via nvm: `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash` then `nvm install --lts`.",
            "Or download from nodejs.org / use your OS package manager.",
        ],
        "remediation": "brew install node   # or: nvm install --lts",
    },
    {
        "id": "npm-not-found",
        "tags": ["node", "npm"],
        "severity": "error",
        "match": r"npm: command not found|command not found: npm|npm ERR! code ENOENT",
        "title": "npm is not installed",
        "why": "npm ships with Node; if it's missing, Node probably isn't installed or PATH is wrong.",
        "fix": [
            "Install Node (npm comes with it) via nvm or nodejs.org.",
            "Verify: `npm --version`.",
        ],
    },
    {
        "id": "npm-eacces",
        "tags": ["node", "npm", "permissions"],
        "severity": "error",
        "match": r"npm ERR! code EACCES|EACCES: permission denied",
        "title": "npm permission denied (EACCES)",
        "why": "npm tried to write global packages into a system directory you don't own (e.g. /usr).",
        "fix": [
            "Never use `sudo npm` - it breaks permissions and security. Set a user-owned prefix: `npm config set prefix ~/.npm-global` and add `~/.npm-global/bin` to PATH.",
            "Better: install Node via nvm so globals live under your home dir; or use `npm i -g` after that.",
        ],
    },
    {
        "id": "npm-network",
        "tags": ["node", "npm", "network"],
        "severity": "error",
        "match": r"npm ERR! code ECONNRESET|npm ERR! network request failed|ETIMEDOUT",
        "title": "npm network/registry error",
        "why": "The registry is unreachable - flaky connection, proxy, or corporate firewall.",
        "fix": [
            "Retry with `npm install --fetch-retries=5 --fetch-timeout=120000`.",
            "If behind a proxy: `npm config set proxy http://host:port` and `https-proxy`.",
            "Or switch registry: `npm config set registry https://registry.npmjs.org/`.",
        ],
    },
    {
        "id": "node-cannot-find-module",
        "tags": ["node"],
        "severity": "error",
        "match": r"Cannot find module ['\"]?(?P<mod>[^'\"]+)",
        "title": "Node can't find module: {mod}",
        "why": "The module isn't resolvable - it's not in node_modules yet, or you're requiring a local file with the wrong relative path/extension.",
        "fix": [
            "Install deps: `npm install` (or `npm install {mod}` for that specific package).",
            "If it's a local file, double-check the relative path and extension (e.g. `./foo.js` vs `./foo`), and run from the project root.",
        ],
    },
    {
        "id": "node-ebadengine",
        "tags": ["node"],
        "severity": "error",
        "match": "EBADENGINE",
        "title": "Node engine version mismatch",
        "why": "The package requires a different Node version than you have.",
        "fix": [
            "Check required version in the error, then install it via nvm: `nvm install <version>`.",
            "Or use `nvm use <version>` to switch for this project.",
        ],
    },
    {
        "id": "go-not-found",
        "tags": ["go"],
        "severity": "error",
        "match": r"go: command not found|command not found: go|'go' is not recognized",
        "title": "Go toolchain not installed",
        "why": "The `go` binary isn't on your PATH.",
        "fix": [
            "Install from go.dev/dl, or via your package manager (`brew install go`).",
            "Add `$(go env GOPATH)/bin` to your PATH.",
        ],
        "remediation": "brew install go   # or download from go.dev/dl",
    },
    {
        "id": "go-no-module",
        "tags": ["go"],
        "severity": "error",
        "match": r"go: cannot find main module|go.mod file not found|missing go.sum entry|unknown revision",
        "title": "Go module / go.mod problem",
        "why": "You're outside a module, or dependencies aren't recorded in go.mod/go.sum.",
        "fix": [
            "Initialize a module: `go mod init <name>`.",
            "Sync deps: `go mod tidy` (also writes go.sum).",
        ],
    },
    {
        "id": "cargo-not-found",
        "tags": ["rust"],
        "severity": "error",
        "match": r"cargo: command not found|command not found: cargo|'cargo' is not recognized",
        "title": "Rust / Cargo not installed",
        "why": "The Cargo build tool isn't on your PATH.",
        "fix": [
            "Install via rustup: `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`.",
            "Then `source $HOME/.cargo/env`.",
        ],
    },
    {
        "id": "rustc-error",
        "tags": ["rust"],
        "severity": "error",
        "match": r"error\[E\d+\]",
        "title": "Rust compilation error",
        "why": "The Rust compiler rejected the code - the error code (E0xxx) points to the exact rule.",
        "fix": [
            "Look up the code: `rustc --explain E<code>` for a detailed description.",
            "Fix per the compiler's note, then `cargo build` again.",
        ],
    },
    {
        "id": "java-not-found",
        "tags": ["java"],
        "severity": "error",
        "match": r"java: command not found|command not found: java|'java' is not recognized",
        "title": "Java not installed",
        "why": "The `java`/`javac` binaries aren't on your PATH.",
        "fix": [
            "Install a JDK (Adoptium/Temurin) or via `sdkman install java`.",
            "Set JAVA_HOME and add `$JAVA_HOME/bin` to PATH.",
        ],
        "remediation": "brew install openjdk   # or: sdkman install java",
    },
    {
        "id": "java-version",
        "tags": ["java"],
        "severity": "error",
        "match": r"UnsupportedClassVersionError|Unsupported major.minor version",
        "title": "Java class file version mismatch",
        "why": "You're running a class compiled with a newer JDK than your runtime JRE.",
        "fix": [
            "Upgrade your JRE to match (or exceed) the compile target.",
            "Or recompile with `-source`/`-target` matching your runtime.",
        ],
    },
    {
        "id": "ruby-bundle-permission",
        "tags": ["ruby"],
        "severity": "error",
        "match": r"Gem::FilePermissionError|Errno::EACCES|You don't have write permissions",
        "title": "Ruby gem permission error",
        "why": "Bundler tried to write gems into a system path you don't own.",
        "fix": [
            "Use a user install: `bundle install --path vendor/bundle` or set `GEM_HOME` to a writable dir.",
            "Or use rbenv/rvm so gems live in your home.",
        ],
    },
    {
        "id": "cc-fatal-include",
        "tags": ["c", "cpp"],
        "severity": "error",
        "match": r"fatal error: .* (No such file or directory|file not found)",
        "title": "C/C++ header not found",
        "why": "The compiler can't locate a header you #include'd (missing -I path or dependency).",
        "fix": [
            "Add the include directory: `-I/path/to/headers`.",
            "Install the missing dev package (e.g. `apt-get install libfoo-dev`).",
        ],
    },
    {
        "id": "cc-undefined-ref",
        "tags": ["c", "cpp"],
        "severity": "error",
        "match": r"undefined reference to",
        "title": "C/C++ undefined reference (linker error)",
        "why": "The linker can't find the implementation of a symbol - usually a missing library or wrong link order.",
        "fix": [
            "Link the library: add `-l<name>` and `-L/path/to/lib`.",
            "Put source/library objects before the `-l` flags on the command line.",
        ],
    },
    {
        "id": "segfault",
        "tags": ["c", "cpp", "runtime"],
        "severity": "error",
        "match": r"Segmentation fault|SIGSEGV",
        "title": "Segmentation fault",
        "why": "The program accessed memory it shouldn't - a null/dangling pointer dereference, buffer overflow, or stack overflow.",
        "fix": [
            "Get a backtrace: `gdb --args ./program args`, then `run` and `bt` to see where it crashed.",
            "Or rebuild with AddressSanitizer (`-fsanitize=address -g`) to pinpoint the exact bad access.",
        ],
    },
    {
        "id": "cmd-not-found",
        "tags": ["shell"],
        "severity": "error",
        "priority": 0,
        "match": r"(?P<cmd>\S+): command not found|command not found: (?P<cmd2>\S+)|'(?P<cmd3>\S+)' is not recognized as an internal or external command",
        "title": "Command `{cmd}` not found",
        "why": "The shell couldn't resolve that name to an executable on your PATH - it may be a typo, not installed, or not on PATH.",
        "fix": [
            "Check spelling and that it's installed: `which {cmd}` (macOS/Linux) / `Get-Command {cmd}` (PowerShell).",
            "Add its install dir to PATH, or invoke it by full path (e.g. `/usr/local/bin/{cmd}`).",
        ],
    },
    {
        "id": "permission-denied",
        "tags": ["shell", "permissions"],
        "severity": "error",
        "match": r"Permission denied|Operation not permitted",
        "title": "Permission denied",
        "why": "The operation was denied because you lack read/write/execute rights on the file/dir, or need elevated privileges (or the file just isn't executable).",
        "fix": [
            "For a script/executable: `chmod +x file` then run `./file`.",
            "For system files: fix ownership with `chown` or run with `sudo` - carefully, and only when you trust the command.",
        ],
        "remediation": "chmod +x <file>",
    },
    {
        "id": "no-space",
        "tags": ["system", "disk"],
        "severity": "error",
        "match": r"No space left on device",
        "title": "Disk is full",
        "why": "The filesystem hit 100% usage, so new writes fail (builds, installs, logs, and Docker images are common culprits).",
        "fix": [
            "Find what's using space: `du -sh * | sort -h` in the relevant dir (try `ncdu` for an interactive view).",
            "Clear caches: `npm cache clean --force`, Docker `docker system prune -a`, or delete old backups/logs.",
        ],
        "remediation": "df -h   # find big files, then clear caches (npm cache clean, docker system prune)",
    },
    {
        "id": "port-in-use",
        "tags": ["network"],
        "severity": "error",
        "match": r"Address already in use.*?[: ]?(?P<port>\d+)|EADDRINUSE|bind: address already in use",
        "title": "Port already in use",
        "why": "Another process already bound that port (servers and Docker often bind 0.0.0.0, so it's taken on all interfaces).",
        "fix": [
            "Find the listener: `lsof -i :PORT` (macOS/Linux) or `Get-NetTCPConnection -LocalPort PORT` (Windows), note its PID.",
            "Stop it (kill the PID) or change your app/config to a free port.",
        ],
        "remediation": "lsof -ti :{port} | xargs -r kill -9   # or change the port in your config",
    },
    {
        "id": "connection-refused",
        "tags": ["network"],
        "severity": "error",
        "match": r"Connection refused|ECONNREFUSED",
        "title": "Connection refused",
        "why": "The connection was refused - either nothing is listening at that host:port, it's bound to the wrong interface, or a firewall/Docker mapping blocks it.",
        "fix": [
            "Confirm the service is running: `curl -v host:port` or `ss -ltnp | grep PORT`.",
            "Check it's bound to the right interface (localhost vs 0.0.0.0) and the correct host/port.",
            "If in Docker, ensure the container port is published (`-p host:container`) and no firewall drops it.",
        ],
    },
    {
        "id": "ssl-cert",
        "tags": ["network", "ssl"],
        "severity": "error",
        "match": r"SSL certificate problem|certificate verify failed|CERTIFICATE_VERIFY_FAILED|unable to verify the first certificate",
        "title": "SSL certificate verification failed",
        "why": "TLS cert validation failed - the cert is self-signed/expired, or your system/language CA bundle is missing or outdated.",
        "fix": [
            "Refresh CA certs: macOS `open /Applications/Python\\ 3.x/Install\\ Certificates.command`; Linux `apt-get install ca-certificates`.",
            "In Python `requests`: point to a bundle via `REQUESTS_CA_BUNDLE=/path` or `import certifi; os.environ['REQUESTS_CA_BUNDLE'] = certifi.where()`.",
            "For a corporate proxy, trust its CA via `REQUESTS_CA_BUNDLE` / `SSL_CERT_FILE` (never disable verification in production).",
        ],
    },
    {
        "id": "zsh-no-matches",
        "tags": ["shell"],
        "severity": "error",
        "match": r"zsh: no matches found",
        "title": "zsh: no matches found (glob didn't expand)",
        "why": "zsh errors when a glob like `*.log` matches nothing, unlike bash which passes it literally.",
        "fix": [
            "Quote the pattern: `command '*.log'`, or escape the `*`.",
            "Or enable null globs: `setopt null_glob` (temporarily).",
        ],
    },
    {
        "id": "bash-syntax-error",
        "tags": ["shell"],
        "severity": "error",
        "match": r"syntax error near unexpected token",
        "title": "Shell syntax error",
        "why": "The shell parser hit an unexpected token - often a missing space around `[`, `>`, or an unclosed quote.",
        "fix": [
            "Check for missing spaces: `[ $x -eq 1 ]` needs spaces; `if[[` should be `if [[`.",
            "Run `shellcheck script.sh` to catch common mistakes.",
        ],
    },
    {
        "id": "docker-daemon",
        "tags": ["docker"],
        "severity": "error",
        "match": r"Cannot connect to the Docker daemon|docker daemon is not running|Is the docker daemon running",
        "title": "Docker daemon isn't running",
        "why": "The Docker engine service isn't running, so the CLI can't reach the daemon over its socket.",
        "fix": [
            "Start it: launch Docker Desktop, or on Linux `sudo systemctl start docker`.",
            "Verify with `docker info` (no error means the daemon is up).",
        ],
        "remediation": "sudo systemctl start docker",
    },
    {
        "id": "docker-permission",
        "tags": ["docker", "permissions"],
        "severity": "error",
        "match": r"permission denied while trying to connect to the Docker daemon socket",
        "title": "Docker socket permission denied",
        "why": "Your user isn't in the `docker` group, so it can't access the daemon's Unix socket.",
        "fix": [
            "Add your user to the group: `sudo usermod -aG docker $USER`, then log out and back in (or `newgrp docker`).",
            "Avoid `sudo docker` long-term; the group membership is the correct fix.",
        ],
        "remediation": "sudo usermod -aG docker $USER",
    },
    {
        "id": "kubectl-context",
        "tags": ["kubernetes"],
        "severity": "error",
        "match": r"Unable to connect to the server|context .* was not found|current context is not set",
        "title": "kubectl has no valid context",
        "why": "kubectl doesn't know which cluster to talk to, or the cluster is unreachable.",
        "fix": [
            "List contexts: `kubectl config get-contexts` and pick one: `kubectl config use-context <name>`.",
            "Point kubectl at a cluster: `kubectl config set-cluster ...` / use your cloud kubeconfig.",
        ],
    },
    # ---- git (additional) ----
    {
        "id": "git-bad-revision",
        "tags": ["git"],
        "severity": "error",
        "match": r"fatal: bad revision",
        "title": "Invalid git revision",
        "why": "The revision or ref you referenced doesn't exist, or isn't fetched.",
        "fix": [
            "Double-check the branch/commit hash spelling.",
            "Run `git rev-parse --verify <rev>` to confirm it exists.",
            "Run `git fetch` if the ref lives on a remote.",
        ],
    },
    {
        "id": "git-bad-object",
        "tags": ["git"],
        "severity": "error",
        "match": r"fatal: bad object",
        "title": "Bad git object",
        "why": "Git can't find the object referenced, often after a shallow or partial fetch.",
        "fix": [
            "Run `git fetch --all` to pull missing objects.",
            "If using a shallow clone, deepen it: `git fetch --unshallow`.",
        ],
    },
    {
        "id": "git-pathspec-no-match",
        "tags": ["git"],
        "severity": "error",
        "match": r"error: pathspec .* did not match any file",
        "title": "Pathspec matched no files",
        "why": "The file/path given on the command line doesn't exist in the tree.",
        "fix": [
            "Check the path spelling and case.",
            "List files with `git ls-files` to confirm the path exists.",
        ],
    },
    {
        "id": "git-merge-in-progress",
        "tags": ["git"],
        "severity": "error",
        "match": r"you need to resolve your current index first|You have unmerged paths",
        "title": "Merge/resolution in progress",
        "why": "A merge or rebase stopped because of conflicts that must be resolved first.",
        "fix": [
            "Resolve conflicts, `git add`, then `git commit` / `git rebase --continue`.",
            "Or abort: `git merge --abort` / `git rebase --abort`.",
        ],
    },
    {
        "id": "git-lock-exists",
        "tags": ["git"],
        "severity": "error",
        "match": r"unable to create '.*\.lock': File exists",
        "title": "Git lock file already exists",
        "why": "A stale .lock file from a crashed/interrupted Git command is blocking the operation.",
        "fix": [
            "Ensure no other git process runs, then delete the lock: `rm <path>.lock`.",
            "If it persists, run `git gc --prune=now`.",
        ],
        "remediation": 'rm -f "$(git rev-parse --git-dir)/index.lock"',
    },
    {
        "id": "git-no-upstream",
        "tags": ["git"],
        "severity": "error",
        "match": r"The current branch .* has no upstream branch",
        "title": "Branch has no upstream",
        "why": "Your local branch isn't tracking a remote branch, so push/pull lacks a target.",
        "fix": [
            "Push and set upstream: `git push -u origin <branch>`.",
            "Or set tracking: `git branch --set-upstream-to=origin/<branch>`.",
        ],
        "remediation": "git push -u origin $(git rev-parse --abbrev-ref HEAD)",
    },
    {
        "id": "git-unrelated-histories",
        "tags": ["git"],
        "severity": "error",
        "match": r"refusing to merge unrelated histories",
        "title": "Unrelated histories",
        "why": "The two branches have no common ancestor (e.g. two separately inited repos).",
        "fix": [
            "Allow it explicitly: `git merge --allow-unrelated-histories`.",
            "Or rebase/reset if you actually want a single history.",
        ],
    },
    {
        "id": "git-local-changes-overwritten",
        "tags": ["git"],
        "severity": "error",
        "match": r"Your local changes would be overwritten",
        "title": "Local changes would be overwritten",
        "why": "A checkout/merge/reset would destroy uncommitted local edits.",
        "fix": [
            "Stash your work: `git stash`, retry, then `git stash pop`.",
            "Or commit your changes first.",
        ],
    },
    {
        "id": "git-dubious-ownership",
        "tags": ["git"],
        "severity": "error",
        "match": r"detected dubious ownership of repository",
        "title": "Dubious repository ownership",
        "why": "Git refuses because the repo is owned by a different user (common on mounted drives).",
        "fix": [
            "Add an exception: `git config --global --add safe.directory <repo-path>`.",
            "Or run as the repo owner / fix directory ownership.",
        ],
    },
    {
        "id": "git-repo-not-found",
        "tags": ["git"],
        "severity": "error",
        "match": r"remote error: access denied or repository not found",
        "title": "Remote repo not found / access denied",
        "why": "The remote URL is wrong, the repo is private, or your credentials lack access.",
        "fix": [
            "Verify the remote URL: `git remote -v`.",
            "Check your access token/SSH key has the needed permission.",
            "Confirm the repo still exists on the host.",
        ],
    },

    # ---- python (additional) ----
    {
        "id": "py-import-name",
        "tags": ["python"],
        "severity": "error",
        "match": r"ImportError: cannot import name",
        "title": "ImportError: cannot import name",
        "why": "The symbol exists in the package but isn't exported at that path (version/API mismatch).",
        "fix": [
            "Check the package version and its current API/docs.",
            "Import from the correct submodule, or pin a compatible version.",
        ],
    },
    {
        "id": "py-pip-no-version",
        "tags": ["python", "pip"],
        "severity": "error",
        "match": r"Could not find a version that satisfies the requirement",
        "title": "pip: no matching version",
        "why": "pip couldn't find a package/version satisfying your constraint (or the index is wrong).",
        "fix": [
            "Check the package name spelling and the version specifier.",
            "Run `pip install <pkg>==` to see available versions.",
            "Ensure you're using the right index: `pip config list`.",
        ],
    },
    {
        "id": "py-pip-timeout",
        "tags": ["python", "pip", "network"],
        "severity": "error",
        "match": r"ReadTimeoutError|pip._vendor.urllib3.exceptions.ReadTimeoutError",
        "title": "pip: read timeout",
        "why": "The package index was too slow to respond while downloading.",
        "fix": [
            "Increase timeout: `pip install --default-timeout=100 <pkg>`.",
            "Use a faster/mirror index, or a local cache.",
        ],
    },
    {
        "id": "py-venv-no-python",
        "tags": ["python"],
        "severity": "error",
        "match": r"venv: Command '.*python.*' not found",
        "title": "venv: Python interpreter not found",
        "why": "The interpreter venv needs isn't on PATH or isn't installed.",
        "fix": [
            "Install Python, or use the full path: `python3 -m venv venv`.",
            "On Debian/Ubuntu also install `python3-venv`.",
        ],
        "remediation": "python3 -m venv venv",
    },
    {
        "id": "py-asyncio-running",
        "tags": ["python"],
        "severity": "error",
        "match": r"asyncio.run\(\) cannot be called from a running event loop|This event loop is already running",
        "title": "asyncio event loop already running",
        "why": "You called asyncio.run() while a loop is already active (common in notebooks).",
        "fix": [
            "Await the coroutine instead of asyncio.run() inside an existing loop.",
            "Use `asyncio.get_event_loop().run_until_complete()` only when no loop runs.",
        ],
    },
    {
        "id": "py-mypy-error",
        "tags": ["python"],
        "severity": "error",
        "match": r"\.py:\d+:\d+: error:",
        "title": "mypy type error",
        "why": "mypy flagged a type inconsistency at the reported line/column.",
        "fix": [
            "Read the error and annotate/cast the type, or fix the mismatch.",
            "Run `mypy --show-error-codes <file>` for details.",
        ],
    },
    {
        "id": "py-recursion-error",
        "tags": ["python"],
        "severity": "error",
        "match": r"RecursionError: maximum recursion depth exceeded",
        "title": "RecursionError",
        "why": "A function calls itself without a proper base case / termination.",
        "fix": [
            "Add or fix the base case / recursion bound.",
            "Convert to an iterative approach, or raise `sys.setrecursionlimit` only if safe.",
        ],
    },
    {
        "id": "py-memory-error",
        "tags": ["python"],
        "severity": "error",
        "match": r"MemoryError",
        "title": "MemoryError",
        "why": "The process ran out of RAM, often from loading huge data or unbounded growth.",
        "fix": [
            "Process data in chunks / stream instead of loading it all at once.",
            "Free references, use generators, or run on a bigger-memory machine.",
        ],
    },
    {
        "id": "py-json-decode",
        "tags": ["python", "encoding"],
        "severity": "error",
        "match": r"json.decoder.JSONDecodeError",
        "title": "JSON decode error",
        "why": "The string you parsed isn't valid JSON (truncated, wrong encoding, or not JSON).",
        "fix": [
            "Print/repr the raw input to inspect it.",
            "Validate with `json.tool` and ensure it's UTF-8 and complete.",
        ],
    },
    {
        "id": "py-value-error",
        "tags": ["python"],
        "severity": "error",
        "match": r"ValueError: invalid literal for (int|float)\(\)",
        "title": "ValueError: invalid literal",
        "why": "You tried to convert a string that doesn't contain a valid number.",
        "fix": [
            "Validate/clean the input before int()/float().",
            "Use `try/except ValueError` and a default or skip.",
        ],
    },
    {
        "id": "py-key-error",
        "tags": ["python"],
        "severity": "error",
        "match": r"KeyError",
        "title": "KeyError",
        "why": "You accessed a dict key that doesn't exist.",
        "fix": [
            "Guard with `dict.get(key)` instead of `d[key]`.",
            "Or check `if key in d:` before access.",
        ],
    },
    {
        "id": "py-index-error",
        "tags": ["python"],
        "severity": "error",
        "match": r"IndexError: list index out of range",
        "title": "IndexError",
        "why": "You indexed a list/sequence at a position beyond its length.",
        "fix": [
            "Check the list length before indexing, or use safe loop bounds.",
            "Iterate rather than indexing manually.",
        ],
    },
    {
        "id": "py-too-many-open-files",
        "tags": ["python", "system"],
        "severity": "error",
        "match": r"OSError: \[Errno 24\] Too many open files",
        "title": "Too many open files",
        "why": "The process opened more file handles than the OS limit allows (often a leak).",
        "fix": [
            "Close files with `with` blocks or `f.close()`.",
            "Raise the limit: `ulimit -n 4096` (or process-wise) and reuse handles.",
        ],
    },

    # ---- node / typescript ----
    {
        "id": "node-tsc-2304",
        "tags": ["node"],
        "severity": "error",
        "match": r"error TS2304: Cannot find name",
        "title": "TypeScript: name not found",
        "why": "TypeScript can't find a declared name (missing import, type, or lib).",
        "fix": [
            "Import the symbol, or declare it (e.g. `declare const x`).",
            "Add the needed `@types/*` package or `lib` in tsconfig.",
        ],
    },
    {
        "id": "node-tsc-2322",
        "tags": ["node"],
        "severity": "error",
        "match": r"error TS2322: Type '.*' is not assignable",
        "title": "TypeScript: type not assignable",
        "why": "You assigned a value whose type isn't compatible with the target's type.",
        "fix": [
            "Adjust the types (cast, widen, or fix the value).",
            "Run `tsc --noEmit` to see all mismatches.",
        ],
    },
    {
        "id": "node-jest-no-module",
        "tags": ["node", "jest"],
        "severity": "error",
        "priority": 2,
        "match": r"Cannot find module '.*' from '.*'",
        "title": "Jest: cannot find module",
        "why": "Jest can't resolve a module from the given file (missing dep, wrong path, or mapper).",
        "fix": [
            "Run `npm install` (or install the specific package).",
            "Check the import path and add a `moduleNameMapper` if aliasing.",
        ],
    },
    {
        "id": "node-eslint-noconfig",
        "tags": ["node"],
        "severity": "error",
        "match": r"ESLint couldn't find a configuration file",
        "title": "ESLint: no config file",
        "why": "ESLint has no eslintrc/flat config in the project or its parents.",
        "fix": [
            "Create one: `npx eslint --init`.",
            "Or set the config path explicitly in your script/CI.",
        ],
    },
    {
        "id": "node-webpack-resolve",
        "tags": ["node"],
        "severity": "error",
        "match": r"Module not found: Error: Can't resolve",
        "title": "Webpack: can't resolve module",
        "why": "Webpack couldn't resolve an import (missing dep, wrong path, or extension).",
        "fix": [
            "Install the dependency: `npm install <pkg>`.",
            "Check the path/extension and `resolve` config in webpack.",
        ],
    },
    {
        "id": "node-nodemon-crash",
        "tags": ["node"],
        "severity": "error",
        "match": r"App crashed - waiting for file changes",
        "title": "nodemon: app crashed",
        "why": "Your app threw an uncaught error at startup; nodemon keeps watching for changes.",
        "fix": [
            "Read the stack trace above and fix the startup error.",
            "Run the app directly (`node index.js`) to see the full error.",
        ],
    },
    {
        "id": "node-unhandled-rejection",
        "tags": ["node"],
        "severity": "error",
        "match": r"UnhandledPromiseRejectionWarning|Unhandled rejection",
        "title": "Unhandled promise rejection",
        "why": "A promise rejected and nothing caught it (Node will exit in newer versions).",
        "fix": [
            "Add `.catch()` or wrap in try/await with try/catch.",
            "Install a global `process.on('unhandledRejection')` handler.",
        ],
    },
    {
        "id": "node-err-require-esm",
        "tags": ["node"],
        "severity": "error",
        "match": r"Error \[ERR_REQUIRE_ESM\]: require\(\) of ES Module",
        "title": "ERR_REQUIRE_ESM: use import",
        "why": "You `require()`d a package that is now ESM-only; CommonJS can't load it directly.",
        "fix": [
            "Use dynamic `import()` instead of `require()`.",
            "Or pick a CJS-compatible version of the package.",
        ],
    },
    {
        "id": "node-npm-elifecycle",
        "tags": ["node", "npm"],
        "severity": "error",
        "match": r"npm ERR! code ELIFECYCLE",
        "title": "npm: script exited with error",
        "why": "An npm lifecycle script (build/test/start) exited non-zero.",
        "fix": [
            "Scroll up to the real error from the script.",
            "Fix that script (or its exit code), then rerun `npm run <script>`.",
        ],
    },

    # ---- docker ----
    {
        "id": "docker-invalid-cmd",
        "tags": ["docker"],
        "severity": "error",
        "match": r"docker: '.*' is not a docker command",
        "title": "Unknown docker command",
        "why": "You typed a subcommand Docker doesn't recognize (typo or unsupported version).",
        "fix": [
            "Run `docker --help` to see valid subcommands.",
            "Check spelling and that your Docker version supports it.",
        ],
    },
    {
        "id": "docker-copy-not-found",
        "tags": ["docker"],
        "severity": "error",
        "match": r"COPY failed: file not found in build context",
        "title": "Docker COPY: file not found",
        "why": "The build context (usually `.`) doesn't contain the file/dir you COPY'd.",
        "fix": [
            "Verify the path relative to the build context and the `.dockerignore`.",
            "Set the correct build context: `docker build -f Dockerfile <context>`.",
        ],
    },
    {
        "id": "docker-push-denied",
        "tags": ["docker"],
        "severity": "error",
        "match": r"denied: requested access to the resource is denied",
        "title": "Docker push denied",
        "why": "You lack push permission or the image name/tag isn't authorized.",
        "fix": [
            "`docker login` and confirm you have push access.",
            "Use the correct namespace: `docker tag <img> <user>/<img>`.",
        ],
        "remediation": "docker login",
    },
    {
        "id": "docker-pull-denied",
        "tags": ["docker"],
        "severity": "error",
        "match": r"Error response from daemon: pull access denied",
        "title": "Docker pull access denied",
        "why": "The image is private or you're not authenticated to pull it.",
        "fix": [
            "`docker login` to the registry.",
            "Use the full image path and confirm pull permission.",
        ],
        "remediation": "docker login",
    },
    {
        "id": "docker-exec-not-found",
        "tags": ["docker"],
        "severity": "error",
        "match": r"exec: \".*\" : executable file not found in \$PATH",
        "title": "Docker: executable not in image",
        "why": "The command you `docker exec`/ENTRYPOINT isn't installed in the image's PATH.",
        "fix": [
            "Install the binary in the image (add to Dockerfile), or use a full path.",
            "Check the image's PATH and base OS.",
        ],
    },

    # ---- kubernetes ----
    {
        "id": "k8s-not-found",
        "tags": ["kubernetes"],
        "severity": "error",
        "match": r"Error from server \(NotFound\)",
        "title": "Kubernetes: resource not found",
        "why": "The requested resource/name doesn't exist in the current namespace.",
        "fix": [
            "Check spelling and namespace: `kubectl get <res> -n <ns>`.",
            "Create it, or switch context/namespace.",
        ],
    },
    {
        "id": "k8s-crashloop",
        "tags": ["kubernetes"],
        "severity": "error",
        "match": r"CrashLoopBackOff",
        "title": "Pod in CrashLoopBackOff",
        "why": "The container keeps crashing on start (bad config, missing dep, or fatal error).",
        "fix": [
            "Inspect: `kubectl logs <pod>` and `kubectl describe pod <pod>`.",
            "Fix the startup error / config, then redeploy.",
        ],
    },
    {
        "id": "k8s-imagepull",
        "tags": ["kubernetes"],
        "severity": "error",
        "match": r"ImagePullBackOff|ErrImagePull",
        "title": "Image pull failure",
        "why": "The node can't pull the image (bad name, private repo, or registry auth).",
        "fix": [
            "Verify the image name/tag and that it exists.",
            "Add an imagePullSecret for private registries.",
        ],
    },
    {
        "id": "k8s-forbidden",
        "tags": ["kubernetes"],
        "severity": "error",
        "match": r"Error from server \(Forbidden\)",
        "title": "Kubernetes: forbidden",
        "why": "Your user/ServiceAccount lacks RBAC permission for that action/resource.",
        "fix": [
            "Check RBAC: `kubectl auth can-i <verb> <res>`.",
            "Grant the role/RoleBinding needed for the action.",
        ],
    },
    {
        "id": "k8s-progress-deadline",
        "tags": ["kubernetes"],
        "severity": "error",
        "match": r"exceeded its progress deadline",
        "title": "Deploy exceeded progress deadline",
        "why": "The rollout didn't become available in time (unhealthy pods, bad image, resources).",
        "fix": [
            "Check rollout: `kubectl rollout status deploy/<name>` and pod events.",
            "Fix the underlying pod issue (image, probes, quotas), then retry.",
        ],
    },
    # ---- go (runtime/build) ----
    {
    "id": "go-panic-nil",
    "tags": ["go"],
    "severity": "error",
    "match": r"panic: runtime error: invalid memory address or nil pointer dereference",
    "title": "Go: nil pointer dereference",
    "why": "A nil pointer was dereferenced - usually an uninitialized struct/interface or a failed lookup.",
    "fix": [
    "Initialize the value before use, or guard with `if x != nil` before dereferencing.",
    "Add a check where the value is produced (e.g. after a map/DB lookup) and handle the missing case.",
    ],
    },
    {
    "id": "go-panic-waitgroup",
    "tags": ["go"],
    "severity": "error",
    "match": r"panic: sync: negative WaitGroup counter",
    "title": "Go: negative WaitGroup",
    "why": "More `wg.Done()` calls than `wg.Add()` - counter went below zero.",
    "fix": [
    "Ensure every goroutine calls `wg.Done()` exactly once for each `wg.Add(1)`.",
    "Use `defer wg.Done()` right after spawning the goroutine.",
    ],
    },
    {
    "id": "go-type-mismatch",
    "tags": ["go"],
    "severity": "error",
    "match": r"cannot use .* \(type .*\) as type .*",
    "title": "Go: type mismatch",
    "why": "You passed a value whose concrete type isn't assignable to the expected type.",
    "fix": [
    "Convert explicitly (e.g. `int(x)`, `string(b)`) or fix the declaration to the right type.",
    "Check for pointer vs value mismatches (e.g. `T` vs `*T`).",
    ],
    },
    {
    "id": "go-undefined",
    "tags": ["go"],
    "severity": "error",
    "match": r"undefined: .*",
    "title": "Go: undefined identifier",
    "why": "The name isn't imported or declared in the current package/scope.",
    "fix": [
    "Import the package that defines it (`import \"pkg\"`) and qualify the name.",
    "Or declare/define the missing identifier, and check for typos.",
    ],
    },
    {
    "id": "go-no-go-files",
    "tags": ["go"],
    "severity": "error",
    "match": r"no Go files in",
    "title": "Go: no Go files in directory",
    "why": "The build target directory contains no `.go` files to compile.",
    "fix": [
    "cd into the package directory that actually has `.go` files.",
    "Or run `go build ./...` / `go run .` from the module root.",
    ],
    },
    {
    "id": "go-test-fail",
    "tags": ["go"],
    "severity": "error",
    "match": r"--- FAIL:",
    "title": "Go test failed",
    "why": "A test case returned a failure (or hit `t.Fatal`/`t.Errorf`).",
    "fix": [
    "Read the `--- FAIL:` block and the `Error:` / `Want`/`Got:` lines for the cause.",
    "Run just that test: `go test -run <TestName> -v`.",
    ],
    },
    {
    "id": "go-signal-killed",
    "tags": ["go"],
    "severity": "error",
    "priority": 2,
    "match": r"signal: killed",
    "title": "Process killed (likely OOM)",
    "why": "The OS killed the process, almost always because it exceeded the memory limit.",
    "fix": [
    "Reduce memory use (stream/slice inputs, cap caches, free references).",
    "Raise the container/process memory limit, or run on a bigger machine.",
    ],
    },
    {
    "id": "go-checksum-mismatch",
    "tags": ["go"],
    "severity": "error",
    "match": r"checksum mismatch",
    "title": "Go: checksum mismatch",
    "why": "go.sum's recorded hash differs from what the module proxy/registry serves.",
    "fix": [
    "Run `go clean -modcache` then `go mod download` to refetch.",
    "If intentional, update go.sum: `go mod tidy` (verify the source is trusted).",
    ],
    },

    # ---- rust ----
    {
    "id": "rust-e0502",
    "tags": ["rust"],
    "severity": "error",
    "match": r"error\[E0502\]: cannot borrow .* as mutable",
    "title": "Rust: borrow conflict (E0502)",
    "why": "You tried to mutably borrow while another borrow is still alive.",
    "fix": [
    "Shrink the scope of the earlier borrow (move the use before the new one).",
    "Restructure so the immutable borrow ends before the mutable one begins.",
    ],
    },
    {
    "id": "rust-e0599",
    "tags": ["rust"],
    "severity": "error",
    "match": r"error\[E0599\]: no method named .* found",
    "title": "Rust: method not found (E0599)",
    "why": "The type doesn't implement the method you called (often a missing trait/import).",
    "fix": [
    "Add the trait to scope: `use some_crate::Trait;` so the method is in scope.",
    "Confirm the type implements the trait, or call the correct method name.",
    ],
    },
    {
    "id": "rust-e0382",
    "tags": ["rust"],
    "severity": "error",
    "match": r"error\[E0382\]: borrow of moved value",
    "title": "Rust: use of moved value (E0382)",
    "why": "Ownership was moved out, then you used the original value again.",
    "fix": [
    "Clone the value before moving (`let y = x.clone();`) if a copy is fine.",
    "Or borrow (`&x`) instead of moving, and adjust lifetimes accordingly.",
    ],
    },
    {
    "id": "rust-e0716",
    "tags": ["rust"],
    "severity": "error",
    "match": r"error\[E0716\]: temporary value dropped while borrowed",
    "title": "Rust: temporary dropped (E0716)",
    "why": "A temporary was created and borrowed, but it was dropped at the end of the statement.",
    "fix": [
    "Bind it to a variable with a longer lifetime: `let v = expr; use(&v);`.",
    "Or pass an owned value instead of a temporary borrow.",
    ],
    },
    {
    "id": "rust-e0308",
    "tags": ["rust"],
    "severity": "error",
    "match": r"error\[E0308\]: mismatched types",
    "title": "Rust: mismatched types (E0308)",
    "why": "Expected one type but got another - common after refactors or wrong literals.",
    "fix": [
    "Convert explicitly (e.g. `x as u32`, `.to_string()`) or fix the expected type.",
    "Run `cargo build` and read `expected` vs `found` in the note.",
    ],
    },
    {
    "id": "rust-unwrap-none",
    "tags": ["rust"],
    "severity": "error",
    "match": r"called `Option::unwrap\(\)` on a `None` value",
    "title": "Rust: unwrap on None",
    "why": "An `Option` was `None` when you called `.unwrap()`/`.expect()`.",
    "fix": [
    "Handle the `None` case with `match`, `if let Some(x)`, or `unwrap_or(default)`.",
    "Verify the value is produced correctly upstream (e.g. lookup/parsing).",
    ],
    },
    {
    "id": "rust-no-macro",
    "tags": ["rust"],
    "severity": "error",
    "match": r"error: cannot find macro .* in this scope",
    "title": "Rust: macro not found",
    "why": "The macro isn't imported into the current module.",
    "fix": [
    "Bring it into scope: `use crate::foo::bar;` or `use macros::my_macro;`.",
    "For standard macros, ensure `#[macro_use]` or the proper `use` path.",
    ],
    },
    {
    "id": "rust-cargo-no-package",
    "tags": ["rust"],
    "severity": "error",
    "match": r"failed to select a version for the requirement",
    "title": "Cargo: dependency not found",
    "why": "Cargo couldn't resolve a dependency version (typo, removed, or no matching version).",
    "fix": [
    "Check the crate name spelling and version in Cargo.toml.",
    "Run `cargo search <crate>` to confirm it exists and pick an available version.",
    ],
    },

    # ---- java ----
    {
    "id": "java-classnotfound",
    "tags": ["java"],
    "severity": "error",
    "match": r"java.lang.ClassNotFoundException",
    "title": "Java: ClassNotFoundException",
    "why": "The class loader couldn't find the class on the classpath at runtime.",
    "fix": [
    "Ensure the JAR/classes containing the class is on the classpath (`-cp`).",
    "Rebuild and confirm the class name/package is correct.",
    ],
    },
    {
    "id": "java-noclassdeffound",
    "tags": ["java"],
    "severity": "error",
    "match": r"java.lang.NoClassDefFoundError",
    "title": "Java: NoClassDefFoundError",
    "why": "A class that was available at compile time is missing at runtime (often a missing dependency).",
    "fix": [
    "Check the runtime classpath for the missing class/JAR.",
    "Ensure all transitive dependencies are packaged (e.g. shading/fat JAR).",
    ],
    },
    {
    "id": "java-nosuchmethod",
    "tags": ["java"],
    "severity": "error",
    "match": r"java.lang.NoSuchMethodError",
    "title": "Java: NoSuchMethodError",
    "why": "A class was compiled against one version but a different (older) version is on the runtime classpath.",
    "fix": [
    "Align dependency versions between compile and runtime.",
    "Run `mvn dependency:tree` / `gradle dependencies` to find the conflicting JAR.",
    ],
    },
    {
    "id": "java-oom",
    "tags": ["java"],
    "severity": "error",
    "match": r"java.lang.OutOfMemoryError",
    "title": "Java: OutOfMemoryError",
    "why": "The JVM ran out of heap (or metaspace/stack) - a leak or too-small limit.",
    "fix": [
    "Increase heap: `-Xmx<size>` (e.g. `-Xmx2g`), and check the specific OOM subtype.",
    "Profile for leaks (heap dump) or cap caches/collections.",
    ],
    },
    {
    "id": "java-javac-notfound",
    "tags": ["java"],
    "severity": "error",
    "match": r"javac: file not found",
    "title": "javac: file not found",
    "why": "The source file you asked javac to compile doesn't exist at that path.",
    "fix": [
    "Check the file path/name and your current directory.",
    "Use the correct relative path, or `*.java` glob within the source dir.",
    ],
    },
    {
    "id": "java-gradle-no-java",
    "tags": ["java"],
    "severity": "error",
    "match": r"Could not determine Java version",
    "title": "Gradle: Java version issue",
    "why": "Gradle couldn't locate a compatible JDK/JAVA_HOME.",
    "fix": [
    "Set `JAVA_HOME` to a JDK Gradle supports, and add `$JAVA_HOME/bin` to PATH.",
    "Or use the Gradle toolchain: `java { toolchain { languageVersion = 17 } }`.",
    ],
    },

    # ---- ruby ----
    {
    "id": "ruby-loaderror",
    "tags": ["ruby"],
    "severity": "error",
    "match": r"LoadError: cannot load such file",
    "title": "Ruby: LoadError",
    "why": "Ruby couldn't `require` the named file - gem not installed or not on the load path.",
    "fix": [
    "Install the gem: `gem install <name>` or add it to the Gemfile and `bundle install`.",
    "Run via bundler so the load path is set: `bundle exec ruby app.rb`.",
    ],
    },
    {
    "id": "ruby-gemfile-not-found",
    "tags": ["ruby"],
    "severity": "error",
    "match": r"Bundler::GemfileNotFound",
    "title": "Bundler: Gemfile not found",
    "why": "Bundler ran from a directory without a Gemfile.",
    "fix": [
    "cd into the project root that contains the Gemfile.",
    "Or create one with `bundle init` if starting a new project.",
    ],
    },
    {
    "id": "ruby-secret-key",
    "tags": ["ruby"],
    "severity": "error",
    "match": r"Missing `secret_key_base`",
    "title": "Rails: missing secret_key_base",
    "why": "Rails needs `secret_key_base` for the environment (often missing in production).",
    "fix": [
    "Set it via credentials: `rails credentials:edit` (or ENV `SECRET_KEY_BASE`).",
    "For production, generate one: `rails secret` and export it.",
    ],
    },
    {
    "id": "ruby-name-error",
    "tags": ["ruby"],
    "severity": "error",
    "match": r"NameError: uninitialized constant",
    "title": "Ruby: uninitialized constant",
    "why": "You referenced a constant that isn't defined or isn't in scope.",
    "fix": [
    "Check the spelling/case and that the defining file is required.",
    "Confirm the module/class is loaded (autoloading path or explicit `require`).",
    ],
    },

    # ---- c / c++ ----
    {
    "id": "cc-linker-symbol",
    "tags": ["c", "cpp"],
    "severity": "error",
    "match": r"ld: symbol\(s\) not found",
    "title": "C/C++: linker symbol not found",
    "why": "The linker can't resolve a symbol - a missing object/implementation or wrong link order.",
    "fix": [
    "Add the source/object that defines the symbol to the link line.",
    "Link the library with `-l<name>` and `-L/path/to/lib`.",
    ],
    },
    {
    "id": "cc-linker-failed",
    "tags": ["c", "cpp"],
    "severity": "error",
    "match": r"clang: error: linker command failed",
    "title": "C/C++: linker command failed",
    "why": "The final link step failed (unresolved symbols, missing libs, or bad flags).",
    "fix": [
    "Read the linker error above for the specific unresolved symbol.",
    "Add the missing `-l`/`-L` flags or object files, then rebuild.",
    ],
    },
    {
    "id": "cc-undeclared",
    "tags": ["c", "cpp"],
    "severity": "error",
    "match": r"error: use of undeclared identifier",
    "title": "C/C++: undeclared identifier",
    "why": "You used a name the compiler hasn't seen a declaration for.",
    "fix": [
    "Include the right header (`#include <...>`) or declare the identifier.",
    "Check for typos and proper namespace qualification (`std::`).",
    ],
    },
    {
    "id": "cc-expected-semi",
    "tags": ["c", "cpp"],
    "severity": "error",
    "match": r"error: expected ';'",
    "title": "C/C++: expected semicolon",
    "why": "A statement or declaration is missing its terminating semicolon.",
    "fix": [
    "Add `;` at the end of the line the compiler points to.",
    "Check the line above too - the error is often reported on the next line.",
    ],
    },
    {
    "id": "cc-double-free",
    "tags": ["c", "cpp"],
    "severity": "error",
    "match": r"free\(\): double free detected",
    "title": "C/C++: double free",
    "why": "The same pointer was passed to `free()` twice - heap corruption.",
    "fix": [
    "Set pointers to `NULL` after `free()` and only free when non-NULL.",
    "Avoid mixing ownership (one owner frees; others don't).",
    ],
    },
    {
    "id": "cc-corrupted-top",
    "tags": ["c", "cpp"],
    "severity": "error",
    "match": r"malloc\(\): corrupted top size",
    "title": "C/C++: heap corruption",
    "why": "A buffer overflow/underflow corrupted the heap's top chunk metadata.",
    "fix": [
    "Find the out-of-bounds write (e.g. off-by-one in an array copy).",
    "Build with AddressSanitizer: `-fsanitize=address` to locate it.",
    ],
    },

    # ---- shell ----
    {
    "id": "shell-fish-unknown",
    "tags": ["shell"],
    "severity": "error",
    "match": r"fish: Unknown command",
    "title": "fish: unknown command",
    "why": "fish couldn't find the command - not installed, not on PATH, or a typo.",
    "fix": [
    "Check the command spelling and that it's installed (`which <cmd>`).",
    "Add its location to `fish_add_path` / `$PATH`.",
    ],
    },
    {
    "id": "shell-bad-substitution",
    "tags": ["shell"],
    "severity": "error",
    "match": r"bash: .*: bad substitution",
    "title": "bash: bad substitution",
    "why": "The `${...}` parameter expansion is malformed or unsupported by the shell.",
    "fix": [
    "Check the syntax inside `${}` (e.g. `${VAR:0:3}` needs bash, not sh).",
    "Avoid invalid operators; use a supported shell or rewrite the expansion.",
    ],
    },
    {
    "id": "shell-unexpected-eof",
    "tags": ["shell"],
    "severity": "error",
    "match": r"syntax error: unexpected end of file",
    "title": "Shell: unexpected EOF",
    "why": "A quoting or block construct wasn't closed (missing `'`, `\"`, `)`, `done`, `fi`).",
    "fix": [
    "Check for an unclosed quote, `$( )`, or control block (`if`/`for`/`while`).",
    "Run `shellcheck script.sh` to pinpoint the unbalanced construct.",
    ],
    },
    {
    "id": "shell-command-subst",
    "tags": ["shell"],
    "severity": "error",
    "match": r"command substitution: .*",
    "title": "Shell: command substitution error",
    "why": "The command inside `$(...)` or backticks failed or had a syntax error.",
    "fix": [
    "Run the inner command on its own to see its real error.",
    "Fix the inner command, then re-evaluate the substitution.",
    ],
    },
    {
    "id": "shell-bash-line",
    "tags": ["shell"],
    "severity": "error",
    "match": r"bash: line \d+: ",
    "title": "bash: error on line",
    "why": "bash reported an error at a specific line of a script - location pointer for the real cause.",
    "fix": [
    "Open the script at the reported line number and inspect the command there.",
    "Run `bash -x script.sh` for a trace, or `shellcheck script.sh`.",
    ],
    },

    # ---- network ----
    {
    "id": "net-ssh-timeout",
    "tags": ["network"],
    "severity": "error",
    "match": r"ssh: connect to host .* port 22: Connection timed out",
    "title": "SSH: connection timed out",
    "why": "No response on port 22 - host down, wrong address, or a firewall dropping packets.",
    "fix": [
    "Verify the host is reachable: `ping <host>` and the correct SSH port.",
    "Check security groups/firewall allow inbound 22 from your IP.",
    ],
    },
    {
    "id": "net-dns",
    "tags": ["network"],
    "severity": "error",
    "match": r"Name or service not known",
    "title": "DNS resolution failure",
    "why": "The hostname couldn't be resolved to an IP - bad DNS config or typo in the host.",
    "fix": [
    "Check the hostname spelling and your DNS servers (`/etc/resolv.conf`, `nslookup`).",
    "Try a known-good resolver or set `nameserver 8.8.8.8` temporarily.",
    ],
    },
    {
    "id": "net-curl-7",
    "tags": ["network"],
    "severity": "error",
    "match": r"curl: \(7\) Failed to connect",
    "title": "curl: connection failed",
    "why": "curl couldn't establish a TCP connection - nothing listening or blocked.",
    "fix": [
    "Confirm the host:port is correct and the server is running.",
    "Check firewalls/proxies and any required `-x` proxy option.",
    ],
    },
    {
    "id": "net-curl-28",
    "tags": ["network"],
    "severity": "error",
    "match": r"curl: \(28\) Operation timed out",
    "title": "curl: operation timed out",
    "why": "The connection was made but the server was too slow to respond.",
    "fix": [
    "Increase the timeout: `curl --max-time <secs>` and retry.",
    "Investigate server load / slow upstream; check proxy latency.",
    ],
    },
    {
    "id": "net-curl-60",
    "tags": ["network"],
    "severity": "error",
    "priority": 2,
    "match": r"curl: \(60\) SSL certificate problem",
    "title": "curl: SSL certificate problem",
    "why": "The server's TLS cert failed validation (self-signed, expired, or wrong CA).",
    "fix": [
    "Update your CA bundle, or point curl at your CA: `curl --cacert <ca.pem>`.",
    "For a known dev host only, bypass with `curl -k` (not for production).",
    ],
    },
    {
    "id": "net-econnreset",
    "tags": ["network"],
    "severity": "error",
    "match": r"Connection reset by peer|ECONNRESET",
    "title": "Connection reset",
    "why": "The remote host abruptly closed the TCP connection (crash, firewall, or idle timeout).",
    "fix": [
    "Check the server logs for a crash or forced disconnect.",
    "Inspect intermediate proxies/firewalls for idle/size limits; retry with backoff.",
    ],
    },
    {
    "id": "net-502",
    "tags": ["network"],
    "severity": "error",
    "match": r"502 Bad Gateway",
    "title": "502 Bad Gateway",
    "why": "A gateway/proxy got an invalid response from the upstream server.",
    "fix": [
    "Check the upstream service is healthy and returning valid responses.",
    "Inspect reverse-proxy/load-balancer config and timeouts.",
    ],
    },
    {
    "id": "net-504",
    "tags": ["network"],
    "severity": "error",
    "match": r"504 Gateway Timeout",
    "title": "504 Gateway Timeout",
    "why": "A gateway/proxy timed out waiting for the upstream server.",
    "fix": [
    "Increase the proxy/gateway timeout for slow upstreams.",
    "Optimize or scale the upstream service so it responds in time.",
    ],
    },
    {
    "id": "net-cors",
    "tags": ["network"],
    "severity": "error",
    "match": r"Access-Control-Allow-Origin|Cross-Origin Request Blocked|CORS",
    "title": "CORS error",
    "why": "The browser blocked a cross-origin request because the server didn't allow it.",
    "fix": [
    "Have the server send `Access-Control-Allow-Origin` for your origin.",
    "For credentials, also set `Access-Control-Allow-Credentials: true`.",
    ],
    },

    # ---- database ----
    {
    "id": "db-postgres-refused",
    "tags": ["database"],
    "severity": "error",
    "match": r"connection refused.*postgres|psycopg2\.OperationalError",
    "title": "Postgres: connection refused",
    "why": "The Postgres server isn't accepting connections at that host/port.",
    "fix": [
    "Confirm Postgres is running and listening (`pg_isready`, `ss -ltnp`).",
    "Check host/port/credentials and that `pg_hba.conf` allows the client.",
    ],
    },
    {
    "id": "db-mysql-access",
    "tags": ["database"],
    "severity": "error",
    "match": r"Access denied for user",
    "title": "MySQL: access denied",
    "why": "The user/password/host combo was rejected by the MySQL server.",
    "fix": [
    "Verify the username, password, and host in your connection string.",
    "Grant privileges: `GRANT ... ON db.* TO 'user'@'host'; FLUSH PRIVILEGES;`.",
    ],
    },
    {
    "id": "db-redis-refused",
    "tags": ["database"],
    "severity": "error",
    "match": r"redis.*Connection refused|redis\.exceptions\.ConnectionError",
    "title": "Redis: connection refused",
    "why": "No Redis server is listening at the configured host/port.",
    "fix": [
    "Start Redis (`redis-server`) and confirm it's listening on the right port.",
    "Check host/port in your client config and any auth/password.",
    ],
    },
    {
    "id": "db-sqlite-locked",
    "tags": ["database"],
    "severity": "error",
    "match": r"database is locked|sqlite3\.OperationalError: database is locked",
    "title": "SQLite: database locked",
    "why": "Another connection holds a write lock and your transaction timed out waiting.",
    "fix": [
    "Reduce concurrent writes, or retry with a small backoff.",
    "Set a busy timeout (`PRAGMA busy_timeout=5000`) and close connections promptly.",
    ],
    },
    {
    "id": "db-mongo-network",
    "tags": ["database"],
    "severity": "error",
    "match": r"MongoNetworkError|MongoTimeoutError",
    "title": "MongoDB: network error",
    "why": "The driver couldn't reach the MongoDB server (down, wrong host, or firewall).",
    "fix": [
    "Verify the connection string host/port and that `mongod` is running.",
    "Check network/firewall and replica-set/`directConnection` settings.",
    ],
    },

    # ---- system ----
    {
    "id": "sys-too-many-open",
    "tags": ["system"],
    "severity": "error",
    "match": r"Too many open files",
    "title": "Too many open files (system)",
    "why": "The process hit the OS file-descriptor limit, often from a leak.",
    "fix": [
    "Close descriptors/handles promptly (use `with`/try-finally).",
    "Raise the limit: `ulimit -n 4096` (or systemd `LimitNOFILE`).",
    ],
    },
    {
    "id": "sys-killed",
    "tags": ["system"],
    "severity": "error",
    "match": r"Out of memory: Killed process|Killed\s*$",
    "title": "OOM kill",
    "why": "The kernel's OOM killer terminated the process for exceeding memory.",
    "fix": [
    "Reduce memory footprint (stream data, cap caches).",
    "Raise the cgroup/container memory limit or move to a bigger instance.",
    ],
    },
    {
    "id": "sys-readonly",
    "tags": ["system"],
    "severity": "error",
    "match": r"Read-only file system",
    "title": "Read-only file system",
    "why": "The filesystem is mounted read-only - disk error, frozen overlay, or revoked write.",
    "fix": [
    "Remount read-write if intended: `mount -o remount,rw /`.",
    "Check disk health / cloud volume state and free space.",
    ],
    },
    {
    "id": "sys-no-route",
    "tags": ["system"],
    "severity": "error",
    "match": r"No route to host",
    "title": "No route to host",
    "why": "The network layer has no path to the destination (down link, bad gateway, or firewall).",
    "fix": [
    "Check local network/interface is up (`ip addr`, `ping` the gateway).",
    "Verify the destination is reachable and not blocked by a firewall.",
    ],
    },

    # ---- package manager ----
    {
    "id": "pm-apt-locate",
    "tags": ["package-manager"],
    "severity": "error",
    "match": r"E: Unable to locate package",
    "title": "apt: package not found",
    "why": "apt couldn't find that package name in the configured indexes.",
    "fix": [
    "Run `sudo apt-get update` to refresh package lists, then retry.",
    "Check the spelling and that the right repository/components are enabled.",
    ],
    },
    {
    "id": "pm-apt-lock",
    "tags": ["package-manager"],
    "severity": "error",
    "match": r"E: Could not get lock",
    "title": "apt: dpkg lock held",
    "why": "Another apt/dpkg process holds the lock (often a background update).",
    "fix": [
    "Wait for the other apt process to finish, or kill stuck ones.",
    "If safe, remove the lock: `sudo rm /var/lib/dpkg/lock*` then `sudo dpkg --configure -a`.",
    ],
    },
    {
    "id": "pm-brew-no-formula",
    "tags": ["package-manager"],
    "severity": "error",
    "match": r"brew: No available formula",
    "title": "Homebrew: no formula",
    "why": "Homebrew has no formula with that name in the active taps.",
    "fix": [
    "Check the package name spelling (`brew search <name>`).",
    "Tap the needed repo: `brew tap <org>/<repo>` if it's a third-party formula.",
    ],
    },
    {
    "id": "pm-yum-no-package",
    "tags": ["package-manager"],
    "severity": "error",
    "match": r"No package.*available",
    "title": "yum: no package available",
    "why": "yum/dnf found no package matching the name in enabled repos.",
    "fix": [
    "Run `yum makecache` / enable the right repo (`yum-config-manager --enable`).",
    "Check the package name and that EPEL/other repos are enabled.",
    ],
    },

    # ---- ci ----
    {
    "id": "ci-gitlab-no-config",
    "tags": ["ci"],
    "severity": "error",
    "match": r"Could not find .gitlab-ci.yml",
    "title": "GitLab CI: missing config",
    "why": "GitLab couldn't locate a `.gitlab-ci.yml` in the repo root for the pipeline.",
    "fix": [
    "Add a `.gitlab-ci.yml` at the repository root and commit it.",
    "Verify the filename and that it's on the branch being built.",
    ],
    },

]

ALL_TAGS = sorted({t for r in RULES for t in r.get("tags", [])})